#!/usr/bin/env bash
export JUPYTER_PORT=${JUPYTER_PORT=8888}

export SPARK_DRIVER_MEMORY=${SPARK_DRIVER_MEMORY=2G}
export SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY=4G}
export SPARK_EXECUTOR_CORES=${SPARK_EXECUTOR_CORES=4}
export SPARK_NUM_EXECUTORS=${SPARK_NUM_EXECUTORS=1}
